### ISSUE TITLE
How to Open remote PDF ?

### ISSUE THREAD

**Issue by BYogesh** [jblough/Android-Pdf-Viewer-Library#34]
Hello,
I am getting a url of the location where the PDF is stored. I want to open the pdf with the pdfviewer. Can I get the guideline to open it as currently I am saving the url in string and then I am passing the string as  the path of the pdf to the Activity through the intent 

```
final Intent readPdf = new Intent(getApplicationContext(), PdfViewerActivity.class);
readPdf.addFlags(Intent.FLAG_ACTIVITY_NEW_TASK);
readPdf.putExtra(PdfViewerActivity.EXTRA_PDFFILENAME, path);
startActivity(readPdf);
```

It shows me PDF does not exists but the pdf is available.
please guide.

**Comment by ndorigatti** [comment]
You have to have the file in the device and locally accessible in order to
use the library since in order to open the file it's using a
RandomAccessFile that needs the file and not a stream.
So you have to download file and then open it

2014-08-19 12:22 GMT+02:00 BYogesh notifications@github.com:

**Comment by BYogesh** [comment]
@ndorigatti Thanks brother ...
